### ISSUE TITLE
Submit to F-droid

### ISSUE THREAD

**Issue by eloyesp** [echowaves/WiSaw#5]
Hi, I've tested the application yesterday and it's just great, it could be a great addition on [F-droid][1], as I think that most of the users interested on find a minimalist alternative to Instagram will certainly look there.

I've found a one year old [request][2] with three issues, but I would like to hear your voice about it.

Regards.

 [1]: https://f-droid.org/
 [2]: https://gitlab.com/fdroid/rfp/issues/904

**Comment by IzzySoft** [comment]
@dmitryame any chance? I still see neither fastlane nor tags, so initially mentioned request at F-Droid is still stalled, waiting for this.

For Fastlane, initally 2 simple files in `fastlane/metadata/android/en-US` would do: `short_description.txt` with a summary not longer than 80 chars (eg "Minimalistic Social Sharing", going by what the creator of our request put), and `full_description.txt` with a more detailed description of what the app is about. Copying again:

```markdown
No registration, no sign in -- just open the app, start taking photos, and see what's posted by other people nearby today.

This is the most minimalistic social sharing possible, yet, it's probably the most relevant one as well. It's relevant in time and space. You only see what may potentially matter to you. You do not choose what you see. As such, you do not have to spend time and effort making connections, describing your profile etc. You just start using it. The feed will always stay relevant for your location and time. If you see something you do not like -- just delete it, which will have an effect of drastically increasing the quality of the content for everyone, reducing the noise.

This works best for events, large and small. Wedding or celebration party, at a beach or a park, student at a campus, or a conference attendee, or a group of fans at a football game -- these all will benefit from WiSaw and will definitely make it a lot more fun.
```

Then, for [tagging](https://github.com/echowaves/WiSaw/releases): just do that whenever you release a new version and have your `build.gradle` updated to reflect its `versionName`. Going by the current one, the tag name would be `v5.10.3`.

Can we get this rolling? Thanks in advance!

**Comment by IzzySoft** [comment]
@dmitryame not even a comment – just closed? Wow. That will certainly win you sympathy :cry: Will have to do the same to the request at F-Droid then, sorry.
